version: 2.1

# testing jobs are all the same, so just use a template
defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/base:10
  steps:
    - attach_workspace:
        at: ~/
    - run:
        command: |
          cd examples/$CIRCLE_JOB
          npm run start
        name: start the server
        background: true
    - run:
        # only record the tests on Cypress Dashboard
        # if the record key is set. Usually it is NOT set
        # for forked pull request because environment variables
        # are not passed to the external PRs
        command: |
          cd examples/$CIRCLE_JOB
          if [ -z "$CYPRESS_RECORD_KEY" ]; then
            npm run cypress:run
          else
            npm run cypress:run -- --record --group $CIRCLE_JOB
          fi
        name: Cypress tests

jobs:
  # a single job that installs dependencies (NPM and Cypress)
  build:
    working_directory: ~/app
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          key: cache-dirs-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "circle.yml" }}
      - run: npm ci
      # run verify and then save cache.
      # this ensures that the Cypress verified status is cached too
      - run: npm run cypress:verify
      - run: npm run stop-only
      - save_cache:
          key: cache-dirs-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "circle.yml" }}
          paths:
            - ~/.npm
            - ~/.cache
      # all other test jobs will run AFTER this build job finishes
      # to avoid reinstalling dependencies, we persist the source folder "app"
      # and the Cypress binary to workspace, which is the fastest way
      # for Circle jobs to pass files
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress

  # dummy job running after all end-to-end tests
  after-tests:
    docker:
      - image: cypress/base:10
    steps:
      - run: echo "all good"

  # a single utility job that can run multiple examples one by one
  test-examples:
    parallelism: 1
    working_directory: ~/app
    docker:
      - image: cypress/base:10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test:ci
  # a single utility script to run multiple examples against Chrome
  test-examples-chrome:
    parallelism: 1
    working_directory: ~/app
    docker:
      - image: cypress/browsers:node8.15.1-chrome73
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run test:ci:chrome

  # define a new job with defaults for each "examples/*" subfolder
  blogs__a11y:
    <<: *defaults
  blogs__application-actions:
    <<: *defaults
  blogs__codepen-demo:
    <<: *defaults
  blogs__direct-control-angular:
    <<: *defaults
  blogs__e2e-api-testing:
    <<: *defaults
  blogs__e2e-snapshots:
    <<: *defaults
  blogs__element-coverage:
    <<: *defaults
  blogs__testing-redux-store:
    <<: *defaults
  blogs__vue-vuex-rest:
    <<: *defaults
  extending-cypress__chai-assertions:
    <<: *defaults
  file-upload-react:
    <<: *defaults
  fundamentals__node-modules:
    <<: *defaults
  fundamentals__fixtures:
    <<: *defaults
  fundamentals__add-custom-command:
    <<: *defaults
  logging-in__csrf-tokens:
    <<: *defaults
  logging-in__html-web-forms:
    <<: *defaults
  logging-in__single-sign-on:
    <<: *defaults
  logging-in__xhr-web-forms:
    <<: *defaults
  logging-in__jwt:
    <<: *defaults
  logging-in__using-app-code:
    <<: *defaults
  preprocessors__grep:
    <<: *defaults
    # in this particular example we want to grep tests
    # and run only tests with name having "@admin"
    environment:
      CYPRESS_grep: '@admin'
  preprocessors__typescript-browserify:
    <<: *defaults
  preprocessors__typescript-webpack:
    <<: *defaults
  server-communication__bootstrapping-your-app:
    <<: *defaults
  stubbing-spying__functions:
    <<: *defaults
  stubbing-spying__window-fetch:
    <<: *defaults
  stubbing-spying__google-analytics:
    <<: *defaults
  testing-dom__drag-drop:
    <<: *defaults
  testing-dom__form-interactions:
    <<: *defaults
  testing-dom__hover-hidden-elements:
    <<: *defaults
  testing-dom__tab-handling-links:
    <<: *defaults
  testing-dom__wait-for-resource:
    <<: *defaults
  unit-testing__application-code:
    <<: *defaults
  unit-testing__react:
    <<: *defaults
  server-communication__env-variables:
    <<: *defaults
  fundamentals__dynamic-tests:
    <<: *defaults
  fundamentals__module-api:
    <<: *defaults

# list all jobs to run and their dependencies here
# and then use this list from workflow definition
all_jobs: &all_jobs
  - build
  - test-examples:
      requires:
        - build
      filters:
        branches:
          only:
            - master

  - test-examples-chrome:
      requires:
        - build
      filters:
        branches:
          only:
            - master

  # when adding new example subfolder with a recipe
  # add its name here to "create" CircleCI job

  # Do not run Codepen demo by default - because it depends on
  # the external service that sometimes gives 502 breaking our tests
  # - blogs__codepen-demo:
  #     requires:
  #       - build

  - blogs__a11y:
      requires:
        - build
  - blogs__application-actions:
      requires:
        - build
  - blogs__direct-control-angular:
      requires:
        - build
  - blogs__e2e-api-testing:
      requires:
        - build
  - blogs__e2e-snapshots:
      requires:
        - build
  - blogs__element-coverage:
      requires:
        - build
  - blogs__testing-redux-store:
      requires:
        - build
  - blogs__vue-vuex-rest:
      requires:
        - build
  - extending-cypress__chai-assertions:
      requires:
        - build
  - file-upload-react:
      requires:
        - build
  - fundamentals__node-modules:
      requires:
        - build
  - fundamentals__add-custom-command:
      requires:
        - build
  - logging-in__csrf-tokens:
      requires:
        - build
  - logging-in__html-web-forms:
      requires:
        - build
  - logging-in__single-sign-on:
      requires:
        - build
  - logging-in__xhr-web-forms:
      requires:
        - build
  - logging-in__jwt:
      requires:
        - build
  - logging-in__using-app-code:
      requires:
        - build
  - preprocessors__grep:
      requires:
        - build
  - preprocessors__typescript-browserify:
      requires:
        - build
  - preprocessors__typescript-webpack:
      requires:
        - build
  - server-communication__bootstrapping-your-app:
      requires:
        - build
  - stubbing-spying__functions:
      requires:
        - build
  - stubbing-spying__window-fetch:
      requires:
        - build
  - stubbing-spying__google-analytics:
      requires:
        - build
  - testing-dom__drag-drop:
      requires:
        - build
  - testing-dom__form-interactions:
      requires:
        - build
  - testing-dom__hover-hidden-elements:
      requires:
        - build
  - testing-dom__tab-handling-links:
      requires:
        - build
  - testing-dom__wait-for-resource:
      requires:
        - build
  - unit-testing__application-code:
      requires:
        - build
  - unit-testing__react:
      requires:
        - build
  - server-communication__env-variables:
      requires:
        - build
  - fundamentals__dynamic-tests:
      requires:
        - build
  - fundamentals__fixtures:
      requires:
        - build
  - fundamentals__module-api:
      requires:
        - build

  # to avoid constantly tweaking required jobs on CircleCI
  # we can have a single job wait on all other test jobs here.
  # CircleCI can then just require this 1 job to pass
  # see https://glebbahmutov.com/blog/parallel-or-not/
  - after-tests:
      requires:
        - build
        - blogs__a11y
        - blogs__application-actions
        - blogs__direct-control-angular
        - blogs__e2e-api-testing
        - blogs__e2e-snapshots
        - blogs__element-coverage
        - blogs__testing-redux-store
        - blogs__vue-vuex-rest
        - extending-cypress__chai-assertions
        - file-upload-react
        - fundamentals__node-modules
        - fundamentals__fixtures
        - fundamentals__dynamic-tests
        - fundamentals__module-api
        - fundamentals__add-custom-command
        - logging-in__csrf-tokens
        - logging-in__html-web-forms
        - logging-in__single-sign-on
        - logging-in__xhr-web-forms
        - logging-in__jwt
        - logging-in__using-app-code
        - preprocessors__grep
        - preprocessors__typescript-browserify
        - preprocessors__typescript-webpack
        - server-communication__bootstrapping-your-app
        - stubbing-spying__functions
        - stubbing-spying__window-fetch
        - stubbing-spying__google-analytics
        - testing-dom__drag-drop
        - testing-dom__form-interactions
        - testing-dom__hover-hidden-elements
        - testing-dom__tab-handling-links
        - testing-dom__wait-for-resource
        - unit-testing__application-code
        - unit-testing__react
        - server-communication__env-variables


workflows:
  version: 2

  # run this workflow on each commit and pull request
  all-recipes:
    jobs: *all_jobs

  # since this is testing a lot of external sites
  # let's run these tests once per day (at night)
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs: *all_jobs
