describe('Drag n Drop', function(){
  beforeEach(function(){
    cy
      .viewport(700, 300)
      .visit('http://localhost:8080/examples/drag_n_drop/index.html')
  })

  it('moves pieces in place', function() {
    return (
      cy
        .pause()
        .get('.piece-1')
          .ttrigger('mousedown', { pageX: 0, pageY: 0 })
          .ttrigger('mousemove', { pageX: 358, pageY: 9 })
          .ttrigger('mouseup')
        .get('.piece-2')
          .ttrigger('mousedown', { pageX: 0, pageY: 80 })
          .ttrigger('mousemove', { pageX: 425, pageY: 9 })
          .ttrigger('mouseup')
        .get('.piece-3')
          .ttrigger('mousedown', { pageX: 0, pageY: 160 })
          .ttrigger('mousemove', { pageX: 492, pageY: 9 })
          .ttrigger('mouseup')
        .get('.piece-4')
          .ttrigger('mousedown', { pageX: 80, pageY: 0 })
          .ttrigger('mousemove', { pageX: 358, pageY: 76 })
          .ttrigger('mouseup')
        .get('.piece-5')
          .ttrigger('mousedown', { pageX: 80, pageY: 80 })
          .ttrigger('mousemove', { pageX: 425, pageY: 76 })
          .ttrigger('mouseup')
        .get('.piece-6')
          .ttrigger('mousedown', { pageX: 80, pageY: 160 })
          .ttrigger('mousemove', { pageX: 492, pageY: 76 })
          .ttrigger('mouseup')
        .get('.piece-7')
          .ttrigger('mousedown', { pageX: 160, pageY: 0 })
          .ttrigger('mousemove', { pageX: 358, pageY: 143 })
          .ttrigger('mouseup')
        .get('.piece-8')
          .ttrigger('mousedown', { pageX: 160, pageY: 80 })
          .ttrigger('mousemove', { pageX: 425, pageY: 143 })
          .ttrigger('mouseup')
        .get('.piece-9')
          .ttrigger('mousedown', { pageX: 160, pageY: 160 })
          .ttrigger('mousemove', { pageX: 492, pageY: 143 })
          .ttrigger('mouseup')
    )
  })
})
